web/mysite/sea-manager-cruise/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views_dir.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", HomeView.as_view(), name="home"),
    path("cuise/", include('main.urls_dir.cruise_urls')),
    path("captain/", include('main.urls_dir.captain_urls')),
    path("location/", include('main.urls_dir.location_urls')),
    path("reservation/", include('main.urls_dir.reservation_urls')),
    path("profile/", include('main.urls_dir.profile_urls')),
]

web/mysite/main/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from main.managers import AppUserManager


class SeaManagerCruiseUser(AbstractBaseUser, PermissionsMixin):

    username = models.CharField(
        max_length=30,
        unique=True
    )

    USERNAME_FIELD = 'username'

    name = models.CharField(
        max_length=30
    )

    surname = models.CharField(
        max_length=30
    )

    email = models.EmailField(
        default='email@example.com'
    )

    EGN = models.CharField(
        max_length=10
    )

    address = models.CharField(
        max_length=30
    )

    phone_number = models.CharField(
        max_length=15
    )

    is_staff = models.BooleanField(
        default=False,
        blank=True,
    )

    objects = AppUserManager()

    def __str__(self):
        return f'{self.name} {self.surname}'


class Captain(models.Model):

    name = models.CharField(
        max_length=30
    )
    surname = models.CharField(
        max_length=30
    )

    profile_picture = models.URLField(
        default='https://gcaptain.com/wp-content/uploads/2017/07/grumpy-ship-captain.jpeg'
    )

    def __str__(self):
        return f'{self.name} {self.surname}'


class CruiseLocation(models.Model):

    name = models.CharField(null=True, blank=True, max_length=15)
    image = models.URLField(default='https://www.planetware.com/wpimages/2021/10/best-tropical-vacations-mauritius-aerial.jpg')
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name


class Cruise(models.Model):

    CRUISE_TYPES = [
        ("Week-long", "Week-long"),
        ("Day-long", "Day-long")
    ]

    from_location = models.ForeignKey(CruiseLocation, related_name="from-location+", on_delete=models.CASCADE)
    to_location = models.ForeignKey(CruiseLocation, related_name="to-location+", on_delete=models.CASCADE)

    type = models.CharField(
        max_length=9,
        choices=CRUISE_TYPES
    )

    captain_name = models.ForeignKey(Captain, on_delete=models.CASCADE)

    departure_date_time = models.DateTimeField()

    econ_total_capacity = models.IntegerField()
    business_total_capacity = models.IntegerField()

    image_main = models.URLField(default='https://images.pexels.com/photos/813011/pexels-photo-813011.jpeg')
    image_1 = models.URLField(default='https://media.istockphoto.com/id/458115989/photo/cruise-ship-in-caribbean-sea.jpg?s=612x612&w=0&k=20&c=wMweujKOnZOpihjorKHEdgqI-LDMJkLF-LpV_FhtUWE=')
    image_2 = models.URLField(default='https://media.istockphoto.com/id/1222173565/photo/cruise-ship-msc-seaside-at-cozumel-island-mexico.jpg?s=612x612&w=0&k=20&c=2w3dQqb196mclsS-oMbFEgYl3r7jgQZFgvKYdASUEMs=')
    image_3 = models.URLField(default='https://media.istockphoto.com/id/516463721/photo/3d-cruise-ship-in-beautiful-ocean-with-blue-sky.jpg?s=612x612&w=0&k=20&c=97aWdauUuFSZwMXZ6Ky4TZDuxg9vhjDb98wFj0vwL3s=')
    image_4 = models.URLField(default='https://media.istockphoto.com/id/1155311911/photo/luxury-cruise-ship-sailing-from-the-port-at-sunrise-across-the-ocean-beautiful-summer.jpg?s=612x612&w=0&k=20&c=im3OvbdWWN-vdwcVcSFMGKpmpbB97Elj5Nva8UXJlmA=')

    def __str__(self):
        return f'{self.type} cruise: {self.from_location} - {self.to_location}'

class Reservation(models.Model):
    TICKET_TYPES = [
        ("Economy", "Economy"),
        ("Business", "Business")
    ]

    cruise = models.ForeignKey(Cruise, on_delete=models.CASCADE)

    cruise_reservee = models.ForeignKey(SeaManagerCruiseUser, on_delete=models.CASCADE)

    ticket_type = models.CharField(
        max_length=8,
        choices=TICKET_TYPES
    )

    number_of_tickets = models.IntegerField(default=1, blank=False, null=False)

    def __str__(self):
        return f'{self.number_of_tickets} reservation(s) for {self.cruise}, by {self.cruise_reservee}'

web/mysite/main/forms.py
from django.forms import ModelForm
from main.models import Cruise, CruiseLocation, Captain, SeaManagerCruiseUser, Reservation
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class CreateCruise(forms.Form):
    class Meta:
        model = Cruise  
        fields = '__all__'


class CreateCaptain(ModelForm):
    class Meta:
        model = Captain
        fields = '__all__'


class CreateLocation(ModelForm):
    class Meta:
        model = CruiseLocation
        fields = '__all__'


class CreateUserForm(ModelForm):
    class Meta:
        model = SeaManagerCruiseUser
        exclude = ('last_login',)


class ReservationCreateForm(ModelForm):
    class Meta:
        model = Reservation
        exclude = ("cruise_reservee",)

web/mysite/main/views_dir/views.py
from typing import Any
from django.contrib.auth import login
from django.contrib.auth.views import LoginView, LogoutView
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.views.generic import FormView, CreateView, DetailView, ListView, UpdateView
from main.models import Cruise, CruiseLocation, Captain, Reservation, SeaManagerCruiseUser
from main.forms import CreateCruise, CreateCaptain, CreateLocation, CreateUserForm, ReservationCreateForm

# Create your views here.

class HomeView(ListView):
    model = Cruise
    context_object_name = 'cruises'

    template_name = "home.html"

    

web/mysite/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sea Manager Cruise</title>
    <style>
        body {
            margin: 0;
            padding: 0;
            font-family: "Avenir Next", "Avenir", sans-serif;
            overflow-x: hidden;
            color: black;
        }

        #menuToggle {
            display: block;
            position: fixed;
            top: 25px;
            left: 25px;
            z-index: 1;
            -webkit-user-select: none;
            user-select: none;
        }

        #menuToggle a {
            text-decoration: none;
            color: white;
            transition: color 0.3s ease;
        }

        #menuToggle a:hover {
            filter: drop-shadow(0 0 0.75rem black);
        }

        #menuToggle input {
            display: block;
            width: 40px;
            height: 32px;
            position: absolute;
            top: -7px;
            left: -5px;
            cursor: pointer;
            opacity: 0;
            z-index: 2;
            -webkit-touch-callout: none;
        }

        #menuToggle span {
            display: block;
            width: 33px;
            height: 4px;
            margin-bottom: 5px;
            position: relative;
            background: black;
            border-radius: 3px;
            z-index: 99;
            transform-origin: 4px 0px;
            transition: transform 0.5s cubic-bezier(0.77, 0.2, 0.05, 1.0),
                background 0.5s cubic-bezier(0.77, 0.2, 0.05, 1.0),
                opacity 0.55s ease;
        }

        #menuToggle span:first-child {
            transform-origin: 0% 0%;
        }

        #menuToggle span:nth-last-child(2) {
            transform-origin: 0% 100%;
        }

        #menuToggle input:checked~span {
            opacity: 1;
            transform: rotate(45deg) translate(-2px, -1px);
            background: #232323;
        }

        #menuToggle input:checked~span:nth-last-child(3) {
            opacity: 0;
            transform: rotate(0deg) scale(0.2, 0.2);
        }

        #menuToggle input:checked~span:nth-last-child(2) {
            transform: rotate(-45deg) translate(0, -1px);
        }

        #menu {
            position: absolute;
            width: 170px;
            margin: -100px 0 0 -50px;
            padding: 50px;
            padding-top: 125px;
            height: 100vh;
            background: rgb(8,0,141);
            background: linear-gradient(94deg, rgba(8,0,141,1) 0%, rgba(0,123,255,1) 26%, rgba(0,212,255,1) 100%); 
            list-style-type: none;
            -webkit-font-smoothing: antialiased;
            transform-origin: 0% 0%;
            transform: translate(-100%, 0);
            transition: transform 0.5s cubic-bezier(0.77, 0.2, 0.05, 1.0);
            display: flex;
            flex-direction: column;
            justify-content: space-between;
        }

        #menu li {
            padding: 10px 0;
            font-size: 22px;
        }

        #menuToggle input:checked~ul {
            transform: none;
        }

        .head, footer {
            background: rgb(8,0,141);
background: linear-gradient(94deg, rgba(8,0,141,1) 0%, rgba(0,123,255,1) 26%, rgba(0,212,255,1) 100%);  
            color: #fff;
            padding: 20px;
            vertical-align: middle;
            filter: drop-shadow(0 0 0.75rem #007bff);
        }  
        .head h1 {
            margin: 0;
        }

        .logout-btn {
            background: red;
            padding: 4px;
            border-radius: 6px;
            filter: drop-shadow(0 0 0.75rem black);
            text-align: center;
        }
    </style>
</head>
<body>
    <header class="head">
        <div id="menuToggle">
            <input type="checkbox" />

            <span></span>
            <span></span>
            <span></span>

            <ul id="menu">
                <div class="links">
                <li style="text-decoration: underline;">Hello {{request.user.username}} :D</li>
                    {% if request.user.is_staff %}
                <a class="subop" href="{% url 'cruise_create' %}">
                    <li>+ Add cruise</li>
                </a>
                {% endif %} 
                <a href="{% url 'captain_list' %}">
                    <li>All captains</li>
                </a>
                {% if request.user.is_staff %}
                <a class="subop" href="{% url 'captain_create' %}">
                    <li>+ Add captain</li>
                </a>
                {% endif %}
    
                <a href="{% url 'location_list' %}">
                    <li>All locations</li>
                </a>
                {% if request.user.is_staff %}
                <a class="subop" href="{% url 'location_create' %}">
                    <li>+ Add location</li>
                </a>
                {% endif %}
    
                </div>
                
                <div class="logout">
                    {% if not request.user.is_authenticated %}
                <a href="{% url 'profile_create' %}">
                    <li>Register</li<>
                        <a href="{% url 'log in' %}">
                    <li>Log In</li>
                </a>
                {% else %}
                    <a href="{% url 'logout' %}">
                        <li class="logout-btn">Log Out</li>
                    </a>
                </div>
                
                {% endif %}
            </ul>
        
        
        </div>
            <div style="text-align: right;" class="logo">
            <h1><a style="color: white; text-decoration: none;" href="{% url 'home' %}">Sea Manager Cruise</a></h1>
        </div>
    </header>
    {% block  base %}
    {%endblock%}
    <footer>Sea Manager Cruise©</footer>
</body>
</html>

web/mysite/templates/captain_views/captain_create.html
{% extends 'forms_template.html' %}
{% block content %}
    <h2>Add a captain</h2>
    <form method="post" action="{% url 'captain_create'%}">

        {% csrf_token %}
        {{form.as_p}}
        <img id="cover-art" src="{{ profile.profile_picture }}" style="width: 100%; height: 100%; object-fit: cover" alt="">

        <button type="submit">Add</button>
    </form>
    <script>
        function notEmpty() {

          let e = document.getElementById("id_profile_picture");
          document.getElementById('cover-art').src = e.value;

        }
        notEmpty()

        document.getElementById("id_profile_picture").onchange = notEmpty;
</script>
{%endblock%}

web/mysite/templates/captain_views/captain_delete.html
{% extends 'forms_template.html' %}
{% block content %}
<h2>DELETE A CAPTAIN?</h2>
<h4 style="color: red;">(ACTION CANNOT BE UNDONE)</h4>
<form method="post" action="{% url 'captain_delete' captain.id %}">

    {% csrf_token %}
    {{ form }}

    <button class="btn btn-danger mt-2" type="submit" style="position: center">Delete</button>
</form>

{%endblock%}

web/mysite/templates/captain_views/captain_edit.html
{% extends 'forms_template.html' %}
{% block content %}
    <h2>Edit a captain</h2>
    
    <form method="post" action="">

        {% csrf_token %}
        {{form.as_p}}

        <img id="cover-art" src="{{ captain.profile_picture }}" style="width: 100%; height: 100%; object-fit: cover" alt="">

        <button type="submit">Add</button>
    </form>
    <script>
        function notEmpty() {

          let e = document.getElementById("id_profile_picture");
          document.getElementById('cover-art').src = e.value;

        }
        notEmpty()

        document.getElementById("id_profile_picture").onchange = notEmpty;
</script>
{%endblock%}

web/mysite/templates/captain_views/captain_list.html
{% extends 'base.html' %}
{% block base%}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        body {
            margin: 0;
            padding: 0;
            font-family: "Avenir Next", "Avenir", sans-serif;
            overflow-x: hidden;
            color: black;
        }

        .greeting {
            margin: 12px;
        }

        .gallery-cell {
            width: 66%;
            height: 70vh;
            margin-right: 10px;
            counter-increment: gallery-cell;
        }

        .header {
            display: flex;
            justify-content: space-between;
            vertical-align: middle;
            background: #0056b3;
            margin-bottom: 24px;
        }

        .gallery-cell img {
            object-fit: cover;
            object-position: center;
            height: 100%;
            width: 100%;
            text-align: left;
        }

        .flickity-page-dots {
            display: none;
        }

        .flickity-prev-next-button {
            display: none;
        }

        .card {
            height: 100%;
            display: flex;
            flex-direction: column;
            text-align: left;
        }

        .top {
            height: 100%;
            margin-bottom: -48px;
            z-index: -1;
        }

        .top img {
            border-radius: 8px;
        }

        .text {
            height: 20%;
            color: black;
            position: relative;
            display: flex;
            flex-direction: column;
            align-items: center;
            text-align: left;
        }

        .text-bg {
            position: absolute;
            background: lightgray;
            border-radius: 8px;
            filter: drop-shadow(0 0 0.75rem black);
            width: 80%;
            height: 250px;
            z-index: -1;
        }

        .text h1,
        h2,
        h3 {
            margin-bottom: 6px;
        }

        .content {
            height: 250px;
        }

        .content h3 {
            margin-bottom: 18px;
        }


        .ul-cards {
            display: flex;
            justify-content: space-between;
            padding: 0;
            flex-wrap: wrap;
            padding: 24px 12px;
        }


        .cruise-card {
            display: flex;
            flex-direction: column;
            align-items: center;
            width: 33%;
            height: 100%;
            margin-top: 24px;
        }

        .cruise-card .top {
            height: 45vh;
            object-fit: cover;
        }

        .cruise-card .top img {
            height: 100%;
            width: 100%;
        }

        #main-content {
            margin-bottom: 250px;
        }

        .cruise-card .bottom {
            color: black;
            background: lightgray;
            border-radius: 8px;
            filter: drop-shadow(0 0 0.75rem black);
            width: 80%;
            height: 10em;
            z-index: -1;
            text-align: center;
        }

        .cruise-card .bottom li {
            padding: 0;
            margin: 0;
        }

        footer {
            background-color: #0056b3;
            width: 100%;
            color: white;
            padding: 12px;
        }

        .site {
            padding: 24px;
        }

        svg {
            height: 15px;
            width: 15px;
        }

        .cruise-card a {
            background-color: #0056b3; 
            padding: 4px 8px; 
            border-radius: 8px; 
            color: white; text-decoration: none;
        }
        .crud {
            visibility: hidden;
        }

        .cruise-card:hover{
            .crud{
                visibility: visible;
            }
        }

    </style>
    <title>Captains</title>
</head>

<body>
    <div class="site">

        <div class="cards">
            <ul class="ul-cards">
                {% for i in captains %}
                <li class="cruise-card">
                    {% if request.user.is_staff or request.user.is_superuser %}
                    <div class="crud">
                        <a href="{% url 'captain_edit' i.id %}">Edit</a>
                        <a style="background-color: red;" href="{% url 'captain_delete' i.id %}">Delete</a>
                    </div>
                        
                    {% endif %}
                    <div class="top">
                        <img src="{{i.profile_picture}}" alt="">
                    </div>
                    <div class="bottom">
                        <h1 style="margin-bottom: 0;"><svg fill="#000000" height="200px" width="200px" version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 461.729 461.729" xml:space="preserve"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <path d="M280.496,63.935V40h0c11.046,0,20-8.954,20-20s-8.954-20-20-20h-99.262c-11.046,0-20,8.954-20,20s8.954,20,20,20v23.935 C93.685,86.056,28.891,165.335,28.891,259.756c0,111.547,90.426,201.973,201.973,201.973s201.973-90.427,201.973-201.973 C432.838,165.335,368.044,86.056,280.496,63.935z M338.227,163.263l-47.606,75.136c2.386,6.675,3.695,13.862,3.695,21.357 c0,35.043-28.408,63.452-63.452,63.452c-7.398,0-14.494-1.279-21.096-3.606l-75.603,47.719c-3.123,1.971-7.195,1.519-9.809-1.091 c-2.614-2.61-3.074-6.681-1.108-9.808l47.681-75.835c-2.268-6.527-3.517-13.532-3.517-20.831c0-35.043,28.408-63.452,63.452-63.452 c7.398,0,14.494,1.279,21.095,3.606l75.365-47.569c3.128-1.974,7.206-1.517,9.819,1.101 C339.757,156.06,340.207,160.139,338.227,163.263z"></path> </g></svg> {{i}}</h1>
                        <p style="text-decoration: underline;">Current cruise:</p>
                        <ul style="list-style: none; padding: 0;">
                            {% if i.curr_cruises %}
                            {% for el in i.curr_cruises %}
                            <li>{{el}}</li>
                            {%endfor%}
                            {% else %}
                            <li>None</li>
                            {%endif%}
                        </ul>
                        
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</body>
{% endblock %}

web/mysite/templates/cruise_views/cruise_create.html
{% extends 'forms_template.html' %}
{% block content %}

    <h2>Add a cruise</h2>
    <form method="post" action="{% url 'cruise_create'%}">

        {% csrf_token %}
        {{form.as_p}}

        <button type="submit">Add</button>
    </form>

<script type="text/javascript">
    document.getElementById("id_departure_date_time").type = "datetime-local";
    document.getElementById("id_arrival_date_time").type = "datetime-local";
</script>

{%endblock%}

web/mysite/templates/cruise_views/cruise_delete.html
{% extends 'forms_template.html' %}
{% block content %}

<h2>DELETE A CRUISE?</h2>
<h4 style="color: red;">(ACTION CANNOT BE UNDONE)</h4>
<form method="post" action="{% url 'cruise_delete' cruise.id %}">

    {% csrf_token %}
    {{ form }}

    <button class="btn btn-danger mt-2" type="submit" style="position: center">Delete</button>
</form>

{%endblock%}

web/mysite/templates/cruise_views/cruise_details.html
{% extends 'base.html' %}
{% block base%}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cruise Details</title>
    <style>
        *{
            margin: 0;
            padding: 0;
        }
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f0f0f0;
            color: #333;
        }

        header {
            background-color: #007BFF;
            color: #fff;
            padding: 1rem;
        }

        section {
            margin: 20px;
        }

        section a {
            background-color: #007BFF;
            color: #fff;
            padding: 10px;
            font-size: 16px;
            border: none;
            cursor: pointer;
            text-decoration: none;
        }

        section a:hover {
            background-color: #0056b3;
        }
        .gallery-small-img img{
            height: 92px;
            width: 112px;
            margin: 10px 0;
            opacity: 0.6;
            cursor: pointer;
            display: block;
        }
        .gallery-small-img img:hover{
            opacity: 1;
        }
        .gallery-small-img{
            float: left;
        }
        .gallery{
            display: flex;
            justify-content: center
        }
        .img-container img{
            height: 500px;
            width: 700px;
        }
        .img-container{
            float: right;
            padding: 10px;
        }

        .site {
            padding: 0 12px;
            display: flex;  
            height: 100%;
        }

        .head {
            background-color: #007BFF;
            color: #fff;
            padding: 1rem;
        }   

    </style>
</head>

<body>
    <div class="site">
        <div class="gallery">

            <div class="gallery-small-img">
                <!-- Placeholder for cruise photos -->
                <img src="{{cruise.image_main}}" onclick="myFunction(this)">
                <img src="{{cruise.image_1}}" onclick="myFunction(this)">
                <img src="{{cruise.image_2}}" onclick="myFunction(this)">
                <img src="{{cruise.image_3}}" onclick="myFunction(this)">
                <img src="{{cruise.image_4}}" onclick="myFunction(this)">
            </div>

            <div class="img-container">
                <img id="imageBox" src="{{cruise.image_main}}">
            </div>
        </div>

        <div class="text">
            <section>
                <h2>Dates of the Cruise</h2>
                <p>{{cruise.departure_date_time}}</p>
            </section>

            <section>
                <h2>Captain</h2>
                <p>{{cruise.captain_name}}</p>
            </section>

            <section>
                <h2>Places We'll Visit</h2>
                <p>{{cruise.from_location}}, {{cruise.to_location}}</p>
            </section>

            <section>
                <h2>Type</h2>   
                <p>{{cruise.type}}</p>
            </section>

            <section>
                <h2>Economy seats left</h2>
                <p>{{econ_cc}} out of {{cruise.econ_total_capacity}}</p>
            </section>

            <section>
                <h2>Buisness seats left</h2>
                <p>{{bus_cc}} out of {{cruise.business_total_capacity}}</p>
            </section>

            <section>
                <a href="{% url 'reserve' cruise.id %}">Purchase Now</a>
            </section>
        </div>
    </div>

    <script>
        function purchaseCruise() {
            // Add logic for the purchase button if needed
            alert("Redirect to the purchase page or perform necessary actions.");
        }
        function myFunction(smallImg) {
            var fullImg = document.getElementById("imageBox");
            fullImg.src = smallImg.src;
        }
    </script>
</body>
{% endblock %}

web/mysite/templates/cruise_views/cruise_edit.html
{% extends 'forms_template.html' %}
{% block content %}

    <h2>Edit a cruise</h2>
    <form method="post" action="{% url 'cruise_edit' cruise.id %}">

        {% csrf_token %}
        {{form.as_p}}

        <button type="submit">Add</button>
    </form>

<script type="text/javascript">
    document.getElementById("id_departure_date_time").type = "datetime-local";
    document.getElementById("id_arrival_date_time").type = "datetime-local";
</script>

{%endblock%}

web/mysite/templates/cruise_views/cruise_list.html
<h1>All cruises:</h1>

{% for cruise in cruises %}
<li> {{ cruise }}  
    <a href="{% url 'reserve' cruise.id %}">Make reservation</a>
    <a href="{% url 'cruise_edit' cruise.id %}">Edit</a> 
    <a href="{% url 'cruise_details' cruise.id %}">Details</a> 
    <a style="color: red;" href="{% url 'cruise_delete' cruise.id %}">Delete</a> </li> 
{% endfor %}

web/mysite/templates/location_views/location_create.html
{% extends 'forms_template.html' %}
{% block content %}
    <h2>Add a location</h2>
    <form method="post" action="{% url 'location_create'%}">

        {% csrf_token %}
        {{form.as_p}}
        <img id="cover-art" src="{{ location.image }}" style="width: 100%; height: 100%; object-fit: cover" alt="">


        <button type="submit">Add</button>
    </form>
    <script>
        function notEmpty() {

          let e = document.getElementById("id_image");
          document.getElementById('cover-art').src = e.value;

        }
        notEmpty()

        document.getElementById("id_image").onchange = notEmpty;
</script>
{%endblock%}

web/mysite/templates/location_views/location_delete.html
{% extends 'forms_template.html' %}
{% block content %}
<h2>DELETE A LOCATION?</h2>
<h4 style="color: red;">(ACTION CANNOT BE UNDONE)</h4>
<form method="post" action="{% url 'location_delete' location.id %}">

    {% csrf_token %}
    {{ form }}

    <button class="btn btn-danger mt-2" type="submit" style="position: center">Delete</button>
</form>
{%endblock%}

web/mysite/templates/location_views/location_edit.html
{% extends 'forms_template.html' %}
{% block content %}
<h2>Edit a location</h2>
    <form method="post" action="">

        {% csrf_token %}
        {{form.as_p}}

        <img id="cover-art" src="{{ location.image }}" style="width: 100%; height: 100%; object-fit: cover" alt="">

        <button type="submit">Submit changes</button>
    </form>
    <script>
        function notEmpty() {

          let e = document.getElementById("id_image");
          document.getElementById('cover-art').src = e.value;

        }
        notEmpty()

        document.getElementById("id_image").onchange = notEmpty;
</script>
{%endblock%}

web/mysite/templates/profile_views/login_page.html
{% extends 'forms_template.html' %}
{% block content %}
    
        <h2>Login</h2>
        {% if form.errors %}
            {{ form.errors }}
        {% endif %}
        <form method="POST">
            {%csrf_token%}
            {{form.username}}
            {{form.password}}
            <button type="submit">Login</button>
        </form>
        
        <p class="switch-form">Don't have an account? <a href="{% url 'profile_create' %}">Register</a></p>

    <script>
        document.getElementById('id_username').placeholder = "Username";
        document.getElementById('id_password').placeholder = "Password";
    </script>
{%endblock%}

web/mysite/templates/reservation_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post" action="{% url 'reserve'%}">

        <br>
        {% csrf_token %}

        Choose your cruise:
        {{form.cruise}}
        <br>
        Choose your ticket type:
        {{form.ticket_type}}

        <br><input type="submit" value="submit"></input>
    </form>
</body>
</html>

web/mysite/templates/reservation_views/reservation_create.html
{% extends 'forms_template.html' %}
{% block content %}
    {% if form.errors %}
    <p style="color: red">{{ form.errors }}</p>
    {% endif %}

    {{pk}}
    <form method="post" action="">

        <br>
        {% csrf_token %}
        {{form.as_p}}

        <br><input type="submit" value="submit"></input>
    </form>
    
{% endblock %}

web/mysite/templates/reservation_views/reservation_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% if form.errors %}
    <p style="color: red">{{ form.errors }}</p>
    {% endif %}

    {{request.user.username}}
    <form method="post" action="{% url 'reservation_edit'%}">

        <br>
        {% csrf_token %}
        {{form.as_p}}

        <br><input type="submit" value="submit"></input>
    </form>
</body>
</html>

web/mysite/templates/reservation_views/reservation_list.html
<h1>All reservations:</h1>

{% for reservation in reservations %}
<li> {{ reservation }}</li>
{% endfor %}